# Generated by Django 2.2.2 on 2019-06-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendContest',
            fields=[
                ('name', models.CharField(default='推荐比赛', max_length=128, primary_key=True, serialize=False, unique=True)),
                ('sign_up_time', models.CharField(max_length=128)),
                ('deadline', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('Senior', '大四'), ('Freshman', '大一'), ('Junior', '大三'), ('Sophomore', '大二')], max_length=128)),
                ('context', models.CharField(default='暂时没有比赛相关内容', max_length=256)),
                ('file', models.FileField(default='avatars/2.jpg', upload_to='file/', verbose_name='比赛相关文件')),
            ],
            options={
                'verbose_name': '推荐比赛',
                'verbose_name_plural': '推荐比赛',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Aris', max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('dynamic', models.CharField(default='这家伙很懒，没有留下什么！', max_length=256)),
                ('number', models.CharField(default='123456', max_length=128, unique=True)),
                ('picture', models.ImageField(default='avatars/1.jpg', upload_to='avatars/', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menber_id', models.CharField(default='None', max_length=128)),
                ('menber_quantity', models.CharField(default='0', max_length=32)),
                ('category', models.CharField(choices=[('game', '游戏'), ('contest', '比赛'), ('traval', '出行'), ('study', '学习')], max_length=128)),
                ('description', models.CharField(default='没有任何描述', max_length=256)),
                ('team_picture', models.ImageField(default='avatars/2.jpg', upload_to='cover/', verbose_name='封面')),
                ('start_time', models.CharField(max_length=128)),
                ('end_time', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('fare', models.CharField(max_length=128)),
                ('favor_quantity', models.CharField(default='0', max_length=32)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolteam.Users')),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
            },
        ),
    ]
