# Generated by Django 2.2.2 on 2019-07-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolteam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromName', models.CharField(max_length=128)),
                ('room', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='recommendcontest',
            name='category',
            field=models.CharField(choices=[('Junior', '大三'), ('Senior', '大四'), ('Freshman', '大一'), ('Sophomore', '大二')], max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('game', '游戏'), ('contest', '比赛'), ('study', '学习'), ('traval', '出行')], max_length=128),
        ),
    ]
