# Generated by Django 2.2.2 on 2019-07-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolteam', '0003_auto_20190701_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendcontest',
            name='category',
            field=models.CharField(choices=[('Freshman', '大一'), ('Sophomore', '大二'), ('Junior', '大三'), ('Senior', '大四')], max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('contest', '比赛'), ('game', '游戏'), ('traval', '出行'), ('study', '学习')], max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='menber_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='menber_quantity',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
